### ISSUE TITLE
DB アンチパターン⑤（１テーブルに複数の情報）

### ISSUE THREAD

**Issue by kmishima16** [kmishima16/praha#14]
解答です
レビューお願いします！
https://different-shock-b76.notion.site/DB-11a27f38df768088adacc5ab17881604?pvs=4

**Comment by tom106gunma** [comment]
@kmishima16 
業務の内容がイメージできていないと陥ってしまいそうだと感じました。
自分自身が経験したことがない分野の設計をする時には注意しようと思います。
