### ISSUE TITLE
データベースモデリング4　解答

### ISSUE THREAD

**Issue by kmishima16** [kmishima16/praha#8]
データベースモデリング４の解答を作成しました。
課題レビューのほどよろしくお願いします。

・作成したER図、クエリ
https://different-shock-b76.notion.site/4-10a27f38df7680e68952c31df32d1790?pvs=4

**Comment by tom106gunma** [comment]
いつも丁寧にまとめられていて、見習わないといけないなと毎回思います。

https://github.com/kmishima16/praha/tree/main/db_modeling_4
を確認したのですが、サンプルデータを投入するDMLが内容です。見落としていたらすいません💦

あと、slackでメンションをつけたメッセージを送るには`@U012AB3CD`のようなslackのユーザーidが必要かもしれないです。
https://api.slack.com/reference/surfaces/formatting#mentioning-users

**Comment by kmishima16** [comment]
@tom106gunma 
早速ご確認いただきましてありがとうございます！

コメントいただいた点、確かにその通りだな、、、と思ったので
以下３点について更新しました！

- slackのユーザidをusersテーブルに追加
https://github.com/kmishima16/praha/commit/dad8c991d6691a227dea204834243c3cc7f1d025#diff-8a0d58c35c6d1ba38ce2832570e251bab93930e29deb96ba12b497e0781b8f3eR2

- DML文を新たに追加
https://github.com/kmishima16/praha/blob/main/db_modeling_4/docker-mysql/script/02_DML.sql

- notionの解答ページを更新
https://different-shock-b76.notion.site/4-10a27f38df7680e68952c31df32d1790?pvs=4
